project:
  type: website
  output-dir: docs

website:
  title: "Intermediate Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - schedule.qmd
      - notes.qmd
      - assignments.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



